### PR TITLE
FYI: my modifications to enable server use as a library

### PR DESCRIPTION
**Pull request by joonas-fi**
Am not expecting you to merge this PR. This is mainly a FYI (don't know if there are better tools to "Show my change on top of upstream")

### CODE REVIEW

**Comment by stapelberg** [comment]
Thanks for sending this! We can definitely get parts (or most) of it merged, though it might be better to hold off until next week, as I’ll be doing a bunch of changes regarding sandboxing/privilege dropping over the next few days :)

**Comment by jsierles** [comment]
Any interest in picking this up again?

**Comment by stapelberg** [comment]
> Any interest in picking this up again?

FWIW, I wouldn’t mind an updated version of this PR to add library support in earnest :)

(The major version will remain at v0 at least until the goals in the README are reached, though.)

**Comment by joonas-fi** [comment]
Sure, I am ready to submit a refreshed PR.

Looking at this again to remember what I did, I had added context cancellation and library-ification of this. Would you like to have them both?

Any guidance of what more I should do / do something differently?

**Comment by stapelberg** [comment]
> Looking at this again to remember what I did, I had added context cancellation and library-ification of this. Would you like to have them both?

Yes please!

> Any guidance of what more I should do / do something differently?

Not for now — let’s get that PR going and we’ll see from there :)

**Comment by joonas-fi** [comment]
This effort continues in new PR https://github.com/gokrazy/rsync/pull/11

**Pull request closed without merging**
